config/routes.rb
Cmwp::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :departments, :only => [:index, :show] do
    resources :deptindices do
      get 'dept_index', :on => :member
    end
  end
  resources :branches, :only => [:index, :show] do
    get 'typebrokers', :on => :member
    resources :branchindices do
      get 'branch_index', :on => :member
    end
  end
  resources :brokers, :only => [:index, :show] do
    resources :brokerindices do
      get 'broker_index', :on => :member
    end
    member do
      get :relbrokers
    end
  end
  resources :categories do
    get 'search', :on => :collection
  end
  
  root :to => 'pages#home'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new' 
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'  
  
  match '/todo',    :to => 'pages#todo'  
  
  

end

app/views/pages/about.html.erb
<div class="page-header">
	<h1>营销团队综合管理视图</h1>
</div>
<div class="hero-unit">
	<p>
		本系统致力于实现和满足人员综合管理查询、跨系统api发布功能。由<%= mail_to 'zishi.mou@sungard.com','牟子实' %>开发维护。 项目采用ruby on rails框架，由TextMate编写，使用mysql5.1社区版数据库。 本项目遵循GPL v3协议，任何组织或个人以及商业软件公司可免费引用/修改/衍生代码，但不得用于商业销售使用目的。
	</p>
</div>
</div>

app/views/pages/brokernew.html.erb
<div class="page-header">
  <h1>营销人员开户</h1>
</div>

<form accept-charset="UTF-8" class="simple_form form-horizontal" id="edit_user_1" method="post" novalidate="novalidate"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /><input name="_method" type="hidden" value="put" /><input name="authenticity_token" type="hidden" value="HgwJwEJbHsTpwFVMXgbNzOAkKUYCJgm/NTKdblhOa9M=" /></div>
	<div class="control-group string optional"><label class="string optional control-label" for="user_name"> 姓名</label><div class="controls"><input class="string optional" id="user_name" name="user[name]" size="50" type="text" value="曹旭东" /></div></div>
	<div class="control-group email optional"><label class="email optional control-label" for="user_email"> Email</label><div class="controls"><input class="string email optional" id="user_email" name="user[email]" size="50" type="email" value="admin@test.org" /></div></div>
	<div class="control-group password optional"><label class="password optional control-label" for="user_password"> 人员代码</label><div class="controls"><input class="password optional" id="user_password" name="user[password]" size="50" /></div></div>
	<div class="control-group password optional"><label class="password optional control-label" for="user_password_confirmation"> 证件类型</label><div class="controls"><input class="string optional" id="user_password_confirmation" name="user[password_confirmation]" size="50" /></div></div>
	<div class="control-group password optional"><label class="password optional control-label" for="user_password_confirmation"> 证件地址</label><div class="controls"><input class="string optional" id="user_password_confirmation" name="user[password_confirmation]" size="50" /></div></div>
	<div class="form-actions">
		<input class="btn btn-primary" name="commit" type="submit" value="下一步" />
		<a href="/" class="btn">取消</a>
	</div>
</form>

app/views/pages/contact.html.erb
<div class="page-header">
	<h1>联系</h1>
</div>
<p>
	请联系：<a href = "http://www.htsec.com/">海通证券销售交易总部</a>
</p>

app/views/pages/help.html.erb
<div class="page-header">
	<h1>帮助</h1>
</div>
<div class="hero-unit">
	<p>
		本项目以及相关说明由<%= link_to 'Github', 'https://github.com/hielf/broker_view' %>托管。</br>
		各种最新使用说明、问题跟踪、项目介绍以及进度计划都可由托管平台获得。
	</p>
</div>

app/views/pages/home.html.erb
<% if signed_in? %>
	<div class="hero-unit">
		<div class="page-header" data-spy="scroll">
		<h1>欢迎您, <%= current_user.name %></h1>
		</div>
			<p>公告：营销综合管理视图ver.1657是为特定客户所开发的业务快速访问通道。通过该项目，能够使得销售交易总部及辖属分支机构执行者直观、快速地接触到逐级管理对象的最新业务进展。也能够帮助各级管理者把握和分析历史情况，从而对新的管理部署做出调整而设计的数据反馈及决策支持系统。拥有低成本、高可靠性和易用性的显著特点。在该项目的基础上，还能够实现对外围系统的准入认证、数据封装对接功能，可以有效减少信息系统开发及运行维护的压力，帮助客户专注业务创新和管理创新。以轻量化和网络化体系构建业务和管理信息资源，达成“数据即服务”的目标。</p>
			</br>
	</div>

<% else %>

<div class="hero-unit">
	<div class="page-header">
	<h1>欢迎您</h1>
	</div>
		<p>公告：营销综合管理视图ver.1657是为特定客户所开发的业务快速访问通道。通过该项目，能够使得销售交易总部及辖属分支机构执行者直观、快速地接触到逐级管理对象的最新业务进展。也能够帮助各级管理者把握和分析历史情况，从而对新的管理部署做出调整而设计的数据反馈及决策支持系统。拥有低成本、高可靠性和易用性的显著特点。在该项目的基础上，还能够实现对外围系统的准入认证、数据封装对接功能，可以有效减少信息系统开发及运行维护的压力，帮助客户专注业务创新和管理创新。以轻量化和网络化体系构建业务和管理信息资源，达成“数据即服务”的目标。</p>
		</br>
		<p>
			 <%= link_to "现在注册", signup_path, :class => "btn btn-primary btn-large btn-block" %>
			 <%= link_to "获取帮助", about_path, :class => "btn btn-large btn-block" %>
		</p>
	</div>

<% end %>

app/views/pages/todo.html.erb
<div class="row-fluid">
	<div class="span5">
		<table class="table table-hover table-bordered">
			<caption><h3>待办事项</h3></caption>
		  <tbody>
			  <tr>
		      <th>客户拜访</th>
		      <th><span class="badge badge-important">2</span></th>
		    </tr>
		    <tr>
		      <td>证券从业资格培训</td>
		      <td><span class="badge badge-warning">1</span></td>
		    </tr>
		  </tbody>
		</table>
	</div>
	<div class="span5">
		<table class="table table-hover table-bordered">
			<caption><h3>信息公告</h3></caption>
		  <!-- <thead>
		    <tr>
		      <th><h4>事项</h4></th>
		      <th></th>
		    </tr>
		  </thead> -->
		  <tbody>
			  <tr>
		      <th>开户审批通过</th>
		      <th><span class="badge badge-important">6</span></th>
		    </tr>
		    <tr>
		      <td>客户回访打分</td>
		      <td><span class="badge badge-warning">18</span></td>
		    </tr>
		  </tbody>
		</table>
	</div>
	<div class="span2">
		<ul class="thumbnails">
			<li>
				<a href="/" class="thumbnail">
					<div>
						<%= image_tag("calendar.tiff", :alt => "日历") %>
					</div>
				</a>
			</li>
		</ul>
	</div>
</div>
<div class="row-fluid">
	<div class="span10">
		<table class="table table-hover table-bordered table-striped">
		  <caption><h3>工作进度</h3></caption>
		  <thead>
		    <tr>
		      <th>标题</th>
		      <th>当前经办人</th>
		    </tr>
		  </thead>
		  <tbody>
		    <tr>
		      <td>12月团队营销活动费用申请</td>
		      <td>销售交易总部</td>
		    </tr>
				<tr>
		      <td>高净值客户拜访工作</td>
		      <td>营业部营销总监</td>
		    </tr>
				<tr>
		      <td>个人信息变更</td>
		      <td>营业部总经理</td>
		    </tr>
		  </tbody>
		</table>
	</div>
</div>

app/views/pages/todolist.html.erb
<div class="page-header">
	<h1>待审批事项</h1>
</div>
<table class="table table-striped">
	<thead>
		<tr>
      <th>业务类型</th>
      <th>处理信息</th>
			<th>流程经办人</th>
			<th></th>
    </tr>
	</thead>
  <tbody>
		<tr>
			<td>营销人员开户审批</td>
			<td>福州群众路营业部</td>
			<td>王春林</td>
			<td>
				<%= link_to "处理", "/", :class => 'btn btn-mini btn-success' %>
			</td>
		</tr>
		<tr>
			<td>营销人员薪酬模板</td>
			<td>福州群众路营业部</td>
			<td>林凯</td>
			<td>
				<%= link_to "处理", "/", :class => 'btn btn-mini btn-success' %>
			</td>
		</tr>
		<tr>
			<td>营业部经纪人绩效考核参数设置</td>
			<td>上海青浦营业部</td>
			<td>金天春</td>
			<td>
				<%= link_to "处理", "/", :class => 'btn btn-mini btn-success' %>
			</td>
		</tr>
		<tr>
			<td>营业部营销费用申请</td>
			<td>义乌营业部</td>
			<td>丁辉</td>
			<td>
				<%= link_to "处理", "/", :class => 'btn btn-mini btn-success' %>
			</td>
		</tr>
	</tbody>
</table>