config/routes.rb
Cmwp::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :departments, :only => [:index, :show] do
    resources :deptindices do
      get 'dept_index', :on => :member
    end
  end
  resources :branches, :only => [:index, :show] do
    get 'typebrokers', :on => :member
    resources :branchindices do
      get 'branch_index', :on => :member
    end
  end
  resources :brokers, :only => [:index, :show] do
    resources :brokerindices do
      get 'broker_index', :on => :member
    end
    member do
      get :relbrokers
    end
  end
  resources :categories do
    get 'search', :on => :collection
  end
  
  root :to => 'pages#home'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new' 
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'  
  
  match '/todo',    :to => 'pages#todo'  
  
  

end

app/models/broker.rb
# encoding: utf-8
class Broker < ActiveRecord::Base
  belongs_to :branch
  has_many :brokerindices
  has_many :brokerrels, :dependent => :destroy,
                        :foreign_key => "rel_broker_id"
  has_many :relbrokers, :through => :brokerrels, :source => :broker
  
  default_scope :order => 'brokers.broker_code'
  
  scope :typebrokers, lambda { |brokertype| where("broker_type = ?", brokertype) } 
  
  def self.search(search)
    if search
      @brokers = Broker.limit(20).find(:all,:conditions => 
                  ['CONCAT(broker_code, \'-\', broker_name) = ? OR broker_code LIKE ? OR broker_name LIKE ?', "#{search}","%#{search}%", "%#{search}%"])
    else
      @brokers = nil
    end
  end
  
  # def branchtypebrokers(broker_type)
  #   self.find_by_broker_type(broker_type)
  # end
end
# == Schema Information
#
# Table name: brokers
#
#  id                   :integer(4)      not null, primary key
#  broker_code          :string(255)
#  broker_name          :string(255)
#  branch_id            :integer(4)
#  broker_type          :string(255)
#  gender               :string(255)
#  age                  :integer(4)
#  broker_level         :string(255)
#  broker_status        :string(255)
#  jobstatus            :string(255)
#  employee_code        :string(255)
#  open_date            :string(255)
#  close_date           :string(255)
#  certificate_type     :string(255)
#  certificate_num      :string(255)
#  certificate_addr     :string(255)
#  mobile               :string(255)
#  phone                :string(255)
#  fax                  :string(255)
#  email                :string(255)
#  birthday             :string(255)
#  bank_account         :string(255)
#  graduate_college     :string(255)
#  graduate_date        :string(255)
#  major                :string(255)
#  earliest_date        :string(255)
#  agreement_begin_date :string(255)
#  agreement_end_date   :string(255)
#  compact_no           :string(255)
#  broker_qualify_no    :string(255)
#  cert_first_date      :string(255)
#  cert_valite_date     :string(255)
#  cert_get_date        :string(255)
#  exam_pass_date       :string(255)
#  risk_balance         :float
#  broker_degree        :string(255)
#  post                 :string(255)
#  job_qualify          :string(255)
#  passed_exam          :string(255)
#  broker_qualify       :string(255)
#  zqbz                 :string(255)
#  personnel_manning    :string(255)
#  region_manager       :string(255)
#  team_name            :string(255)
#  remark               :text
#  created_at           :datetime
#  updated_at           :datetime
#  avatar               :string(255)
#

app/controllers/brokers_controller.rb
# encoding: utf-8
class BrokersController < ApplicationController
  before_filter :authenticate, :only => [:index, :show]
  
  def show
    @broker = Broker.find(params[:id])
    @title  = @broker.broker_code + " - " + @broker.broker_name
    @branch = @broker.branch
    @father_department = @branch.department
    @salary_months = @broker.brokerindices.limit(3).where(:indextype => 2009).reverse_order
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @broker }
    end
  end
  
  def index
    # @categories = Broker.order(:broker_code).where("broker_code LIKE ?", "#{params[:term]}")
    # render json: @categories.map(&:broker_code)
  end
  
  def relbrokers
    @title = "关联帐户"
    @broker = Broker.find(params[:id])
    @brokers = @broker.relbrokers
    render 'categories/search'
  end
end

app/helpers/brokers_helper.rb
# encoding: utf-8
module BrokersHelper
  
  def avatar
    @broker = Broker.find(params[:id])
    if !@broker.avatar.nil?
      image_tag(@broker.avatar, :alt => @broker.broker_name, :size => "90x90" )
    else
      image_tag("nobody.gif", :alt => @broker.broker_name, :size => "90x90" )
    end 
  end
  
  def level_detect(month)
    prev_month = (month.to_s + "01").to_date.prev_month.strftime("%Y%m")
    @broker = Broker.find(params[:id])
    @current_level = @broker.brokerindices.where(:indextype => '6001', :month_id => month).first.occursum.to_i
    @previous_level = @broker.brokerindices.where(:indextype => '6001', :month_id => prev_month).last.occursum.to_i
    if @current_level > @previous_level
      image_tag("level_up.gif", :alt => "升级", :size => "110x111" )
    elsif @current_level < @previous_level
      image_tag("level_down.gif", :alt => "降级", :size => "110x111" )
    else
      image_tag("level_remain.gif", :alt => "维持", :size => "110x111" )
    end
  end
  
  def broker_salary(month)
    @broker = Broker.find(params[:id])
    @broker_salary = @broker.brokerindices.where(:month_id => month)
  end
end

app/views/brokers/_broker.html.erb
<div>
	<ul class="thumbnails">
		<li>
			<a href="<%= broker_path(broker) %>" class="thumbnail">
				<div class="avatar-small">
					<% if !broker.avatar.nil? %>
     				<%= image_tag(broker.avatar, :alt => broker.broker_name, :size => "80x80" ) %>
					<% else %>
						<%= image_tag("nobody.gif", :alt => broker.broker_name, :size => "80x80" ) %>
					<% end %>
				</div>
			</a>
		</li>
		<li>
			<div>
				<h4>
				<%= link_to broker.broker_code + " " +broker.broker_name, broker_path(broker) %>
				</h4>
			</div>
			<div>
				状态: <%= broker.broker_status %>
			</div>
			<div>
				级别: <%= broker.broker_level %>
			</div>
		</li>
	</ul>
	<ul class="common-divider"></ul>
</div>

app/views/brokers/_broker_salary.html.erb
<table class="table table-hover">
 	<!-- <caption><h3>薪酬报告</h3></caption> -->
  <thead>
    <tr>
      <th></th>
      <th>业绩收入</th>
			<th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>总净佣金:</td>
			<td colspan="5"><%= @broker_salary.find_by_indextype(2001) && @broker_salary.find_by_indextype(2001).occursum || 0 %></td>
    </tr>
		<tr>
			<td>一般净佣金:</td>
			<td><%= @broker_salary.find_by_indextype(2002) && @broker_salary.find_by_indextype(2002).occursum || 0 %></td>
			<td>融资融券产品净佣金:</td>
			<td><%= @broker_salary.find_by_indextype(2003) && @broker_salary.find_by_indextype(2003).occursum || 0 %></td>
			<td>报价回购销售利润:</td>
			<td><%= @broker_salary.find_by_indextype(2004) && @broker_salary.find_by_indextype(2004).occursum || 0 %></td>
		</tr>
		<tr>
      <td>总成交量:</td>
			<td colspan="5"><%= @broker_salary.find_by_indextype(2005) && @broker_salary.find_by_indextype(2005).occursum || 0 %></td>
    </tr>
		<tr>
			<td>一般成交量:</td>
			<td><%= @broker_salary.find_by_indextype(2006) && @broker_salary.find_by_indextype(2006).occursum || 0 %></td>
			<td>融资融券产品成交量:</td>
			<td><%= @broker_salary.find_by_indextype(2007) && @broker_salary.find_by_indextype(2007).occursum || 0 %></td>
			<td>报价回购日均保有量:</td>
			<td><%= @broker_salary.find_by_indextype(2008) && @broker_salary.find_by_indextype(2008).occursum || 0 %></td>
		</tr>
  </tbody>
	<thead>
    <tr>
      <th></th>
      <th colspan="5">报酬支出</th>
    </tr>
  </thead>
	<tbody>
		<tr>
      <td>税前工资:</td>
			<td colspan="5"><%= @broker_salary.find_by_indextype(2009) && @broker_salary.find_by_indextype(2009).occursum || 0 %></td>
    </tr>
		<tr>
			<td>基本工资:</td>
			<td><%= @broker_salary.find_by_indextype(2010) && @broker_salary.find_by_indextype(2010).occursum || 0 %></td>
			<td>佣金提成:</td>
			<td><%= @broker_salary.find_by_indextype(2011) && @broker_salary.find_by_indextype(2011).occursum || 0 %></td>
			<td>产品销售奖励:</td>
			<td><%= @broker_salary.find_by_indextype(2012) && @broker_salary.find_by_indextype(2012).occursum || 0 %></td>
		</tr>
	</tbody>
	<thead>
    <tr>
      <th></th>
      <th colspan="5">风险金</th>
    </tr>
  </thead>
	<tbody>
		<tr>
      <td>当月余额:</td>
			<td colspan="5"><%= @broker_salary.find_by_indextype(2013) && @broker_salary.find_by_indextype(2013).occursum || 0 %></td>
    </tr>
		<tr>
			<td>当月留存:</td>
			<td><%= @broker_salary.find_by_indextype(2014) && @broker_salary.find_by_indextype(2014).occursum || 0 %></td>
			<td>当月返还:</td>
			<td><%= @broker_salary.find_by_indextype(2015) && @broker_salary.find_by_indextype(2015).occursum || 0 %></td>
			<td>当月扣减:</td>
			<td><%= @broker_salary.find_by_indextype(2016) && @broker_salary.find_by_indextype(2016).occursum || 0 %></td>
		</tr>
	</tbody>
	<thead>
    <tr>
      <th></th>
      <th colspan="5">薪酬调整</th>
    </tr>
  </thead>
	<tbody>
		<tr>
      <td>调整发:</td>
			<td colspan="2"><%= @broker_salary.find_by_indextype(2017) && @broker_salary.find_by_indextype(2017).occursum || 0 %></td>
			<td>调整扣:</td>
			<td colspan="2"><%= @broker_salary.find_by_indextype(2017) && @broker_salary.find_by_indextype(2017).occursum || 0 %></td>
    </tr>
	</tbody>
</table>

app/views/brokers/_brokerchart1.html.erb
<script type="text/javascript" charset="utf-8">
$(function() {
	showChartResult1(1003,1004);
});

$('#nav-broker-cust button').click( function(e) {
	var selected = $(this).attr('value');
	// console.log(selected);
	showChartResult1(1003,1004);
});

function showChartResult1 (v,w) {
		var _dept,_url,_width,_url2
		_broker = <%= @broker.id %>
		_url = '/brokers/' + _broker + '/brokerindices/' + v + '/broker_index.json'
		_url2 = '/brokers/' + _broker + '/brokerindices/' + w + '/broker_index.json'
		// console.log(_url2);
		_width = document.getElementById("tab_page").offsetWidth;
	  return $.get(_url, function(data) {
			return $.get(_url2, function(data_2) {
			var chart, _month
			    _month = [];
					data.map(function(y) {
													_month.push(y.month);
							          })
			new Highcharts.Chart({
				chart: {
					renderTo: "chart_1",
					type: 'column',
					zoomType: 'x',
					width: _width
				},
				title: {
					text: "客户情况"
				},
				xAxis: {
					categories: _month,
					maxZoom: 1,
					// tickInterval: 3
				},
				yAxis: {
					title: {
						text: "客户数"
					},
					min: 0,
					labels: {
								formatter: function() {
								   return this.value;
								}
							}
				},
				credits: {
					enabled: false
				},
				series: [
				{
				data: 	
					(function() {
				                var _results;
				                _results = [];
				                data.map(function(y) {
																				_results.push(y.total);
														          })
				                return _results;
				              })(),
					name: "客户总数",
				},
				{
				data: 	
					(function() {
				                var _results;
				                _results = [];
				                data_2.map(function(y) {
																				_results.push(y.total);
														          })
				                return _results;
				              })(),
					name: '新增客户数',
				}
				]
			})
		});
  });
}
</script>

app/views/brokers/_brokerchart4.html.erb
<script type="text/javascript" charset="utf-8">
$(function() {
	showChartResult4(6004);
});

$('#nav-broker-point button').click( function(e) {
	var selected = $(this).attr('value');
	// console.log(selected);
	showChartResult4(6004);
});

function showChartResult4 (v) {
		var _dept,_url,_width
		_broker = <%= @broker.id %>
		_url = '/brokers/' + _broker + '/brokerindices/' + v + '/broker_index.json'
		// console.log(_url2);
		_width = document.getElementById("tab_page").offsetWidth;
	  return $.get(_url, function(data) {
			var chart, _month
			    _month = [];
					data.map(function(y) {
													_month.push(y.month);
							          })
			new Highcharts.Chart({
				chart: {
					renderTo: "chart_4",
					type: 'line',
					width: _width
				},
				title: {
					text: "个人考核情况"
				},
				xAxis: {
					categories: _month,
					// tickInterval: 3
				},
				yAxis: {
					title: {
						text: "考核分值"
					},
					min: 0,
					labels: {
								formatter: function() {
								   return this.value;
								}
							}
				},
				credits: {
					enabled: false
				},
				series: [
				{
				data: 	
					(function() {
				                var _results;
				                _results = [];
				                data.map(function(y) {
																				_results.push(y.total);
														          })
				                return _results;
				              })(),
					name: "总绩效考核得分",
				}
				]
			})
  });
}
</script>

app/views/brokers/_brokertable1.html.erb
<table id="_table1" class="table table-bordered">

</table>
<script type="text/javascript" charset="utf-8">
$(function() {
	var curmonth = <%= Time.now.strftime("%Y%m") %>
	showTableResult1(curmonth);
});

$('#nav-broker-point button').click( function(e) {
	var selected = $(this).attr('value');
	showTableResult1(selected);
});

function clearRows1(){  
    var tableLen = document.getElementById('_table1').rows.length;  
    if(tableLen > 0){  
        for(var i=0; i<tableLen; i++){  
            document.getElementById('_table1').deleteRow(tableLen-i-1);  
        }  
    }  
}

function showTableResult1 (v) {
	_broker = <%= @broker.id %>
	clearRows1();  
	var _table = document.getElementById("_table1");  
	var _container,_row,_cell,_url1,_url2,_url3,_url4;
	//table head
	_container = document.createElement("thead");
	document.getElementById("_table1").appendChild(_container);  
	_row = document.createElement("tr");  
	_container.appendChild(_row);  
	_cell = document.createElement("th");  
	_row.appendChild(_cell);
	_cell = document.createElement("th");  
	_cell.innerText = v;  
	_row.appendChild(_cell);

	_url1 = '/brokers/' + _broker + '/brokerindices/5001/broker_index.json'
	_url2 = '/brokers/' + _broker + '/brokerindices/5002/broker_index.json'
	_url3 = '/brokers/' + _broker + '/brokerindices/5003/broker_index.json'
	_url4 = '/brokers/' + _broker + '/brokerindices/5004/broker_index.json'

	return $.get(_url1, function(data_1) {
		return $.get(_url2, function(data_2) {
			return $.get(_url3, function(data_3) {
				return $.get(_url4, function(data_4) {
					var data_1_1, data_2_1, data_3_1, data_4_1
					for(var i in data_1){   
					if (data_1[i].month == v)
						data_1_1 = data_1[i],
						data_2_1 = data_2[i],
						data_3_1 = data_3[i],
						data_4_1 = data_4[i]
					 }
					//table body
					_container = document.createElement("tbody");
					document.getElementById("_table1").appendChild(_container);  
					_row = document.createElement("tr");
					_cell = document.createElement("td");  
					_cell.innerText = data_1_1.subtitle;  
					_row.appendChild(_cell);
					_container.appendChild(_row);  
					_cell = document.createElement("td");
					_cell.innerText = data_1_1.total;  
					_row.appendChild(_cell);
					
					_row = document.createElement("tr");
					_cell = document.createElement("td");  
					_cell.innerText = data_2_1.subtitle;  
					_row.appendChild(_cell);
					_container.appendChild(_row);  
					_cell = document.createElement("td");
					_cell.innerText = data_2_1.total;  
					_row.appendChild(_cell);
					
					_row = document.createElement("tr");
					_cell = document.createElement("td");  
					_cell.innerText = data_3_1.subtitle;  
					_row.appendChild(_cell);
					_container.appendChild(_row);  
					_cell = document.createElement("td");
					_cell.innerText = data_3_1.total;  
					_row.appendChild(_cell);
					
					_row = document.createElement("tr");
					_cell = document.createElement("td");  
					_cell.innerText = data_4_1.subtitle;  
					_row.appendChild(_cell);
					_container.appendChild(_row);  
					_cell = document.createElement("td");
					_cell.innerText = data_4_1.total;  
					_row.appendChild(_cell);
					});
				});
			});
	  });
}
</script>

app/views/brokers/_brokertable2.html.erb
<div class="level-img">
</div>
<table id="_table2" class="table table-bordered">
</table>
<script type="text/javascript" charset="utf-8">
$(function() {
	var curmonth = <%= Time.now.strftime("%Y%m") %>
		showTableResult2(curmonth);
		imgchg1(curmonth);
});

$('#nav-broker-point button').click( function(e) {
	var selected = $(this).attr('value');
		showTableResult2(selected);
		imgchg1(selected);
});

function imgchg1 (m) {
	var _url1;
	_url1 = '/brokers/' + _broker + '/brokerindices/6001/broker_index.json'
	return $.get(_url1, function(data_1) {
		var data_1_1,data_2_1
		for(var i in data_1){   
		if (data_1[i].month == m)
			data_1_1 = data_1[i],
			data_2_1 = data_1[i-1]
		 }
		var flag
		if (data_1_1.total > data_2_1.total)
			flag = 1
		else if (data_1_1.total < data_2_1.total)
		  flag = 2
		else 
		  flag = 0
		
		switch (flag)
		  {
		   case 1:
		     return $('.level-img').replaceWith('<div class="level-img"><img src="/assets/level_up.gif"></div>');
		     break
		   case 2:
		     return $('.level-img').replaceWith('<div class="level-img"><img src="/assets/level_down.gif"></div>');
		     break
		   case 0:
		     return $('.level-img').replaceWith('<div class="level-img"><img src="/assets/level_remain.gif"></div>');
		     break
		   default:
		     return $('.level-img').replaceWith('<div class="level-img"><img src="/assets/level_remain.gif"></div>');
			}
	});
}

function clearRows2(){  
    var tableLen = document.getElementById('_table2').rows.length;  
    if(tableLen > 0){  
        for(var i=0; i<tableLen; i++){  
            document.getElementById('_table2').deleteRow(tableLen-i-1);  
        }  
    }  
}

function showTableResult2 (v) {
	_broker = <%= @broker.id %>
	clearRows2();  
	var _table = document.getElementById("_table2");  
	var _container,_row,_cell,_url1,_url2,_url3,_url4;
	//table head
	_container = document.createElement("thead");
	document.getElementById("_table2").appendChild(_container);  
	_row = document.createElement("tr");  
	_container.appendChild(_row);  
	_cell = document.createElement("th");  
	_row.appendChild(_cell);
	_cell = document.createElement("th");  
	_cell.innerText = v;  
	_row.appendChild(_cell);

	_url1 = '/brokers/' + _broker + '/brokerindices/6001/broker_index.json'
	_url2 = '/brokers/' + _broker + '/brokerindices/6002/broker_index.json'
	_url3 = '/brokers/' + _broker + '/brokerindices/6003/broker_index.json'
	_url4 = '/brokers/' + _broker + '/brokerindices/6004/broker_index.json'

	return $.get(_url1, function(data_1) {
		return $.get(_url2, function(data_2) {
			return $.get(_url3, function(data_3) {
				return $.get(_url4, function(data_4) {
					var data_1_1, data_2_1, data_3_1, data_4_1
					for(var i in data_1){   
					if (data_1[i].month == v)
						  data_1_1 = data_1[i]
					 	 }
					for(var j in data_2){
						if (data_2[j].month == v)
							data_2_1 = data_2[j]
						 }
					for(var l in data_3){
						if (data_3[l].month == v)
							data_3_1 = data_3[l]
						 }
					for(var p in data_4){
						if (data_4[p].month == v)
							data_4_1 = data_4[p]
						 }
					//table body
					_container = document.createElement("tbody");
					document.getElementById("_table2").appendChild(_container);  
					_row = document.createElement("tr");
					_cell = document.createElement("td");  
					_cell.innerText = "定级结果";  
					_row.appendChild(_cell);
					_container.appendChild(_row);  
					_cell = document.createElement("td");
					_cell.innerText = data_1_1.subtitle;  
					_row.appendChild(_cell);
					
					_row = document.createElement("tr");
					_cell = document.createElement("td");  
					_cell.innerText = data_2_1.subtitle;  
					_row.appendChild(_cell);
					_container.appendChild(_row);  
					_cell = document.createElement("td");
					_cell.innerText = data_2_1.total;  
					_row.appendChild(_cell);
					
					_row = document.createElement("tr");
					_cell = document.createElement("td");  
					_cell.innerText = data_3_1.subtitle;  
					_row.appendChild(_cell);
					_container.appendChild(_row);  
					_cell = document.createElement("td");
					_cell.innerText = data_3_1.total;  
					_row.appendChild(_cell);
					
					_row = document.createElement("tr");
					_cell = document.createElement("td");  
					_cell.innerText = data_4_1.subtitle;  
					_row.appendChild(_cell);
					_container.appendChild(_row);  
					_cell = document.createElement("td");
					_cell.innerText = data_4_1.total;  
					_row.appendChild(_cell);
					});
				});
			});
	  });
}
</script>

app/views/brokers/_brokertypes.html.erb
<li><%= link_to broker.broker_code + " " +broker.broker_name, broker_path(broker) %></li>
<li><%= broker_types.broker_type %></li>

app/views/brokers/_sidebarbroker1.html.erb
<div>
	<div class="sidebar-nav well">
			<ul class="thumbnails">
				<li style="margin-left: 0px; margin-bottom: 0px;">
					<a href="<%= broker_path(@broker) %>" class="thumbnail">
						<div class="avatar">
		     			<%= avatar %>
						</div>
					</a>
				</li>
				<li style="margin-bottom: 0px; margin-top: 70px;">
					<h4><%= @broker.broker_name %></h4>
				</li>
			</ul>
			<address>
				<h5>
					年龄：<%= @broker.age %></br>
					性别：<%= @broker.gender %></br>
					手机：<%= @broker.mobile %></br>
					邮箱：<%= mail_to @broker.email %></br>
					状态：<%= @broker.broker_status %></br>
					级别：<%= @broker.broker_level %></br>
					<% if @broker.brokerrels.any? %>
					关联帐户：<a href="<%= relbrokers_broker_path(@broker) %>"><%= @broker.brokerrels.count %></a>
					<% end %>
				</h5>
			</address>
			<ul class="common-divider"></ul>
	</div>
</div>

app/views/brokers/_sidebarbroker2.html.erb
<div>
	<div class="sidebar-nav">
		<ul class="unstyled">
			<blockquote>
			  <p>营销人员资料修改</p>
			  <small>经纪业务管理岗 测试人员</small>
			</blockquote>
			<blockquote>
			  <p>经纪关系挂接</p>
			  <small>李瑾艳</small>
			</blockquote>
		</ul>
	</div>
</div>

app/views/brokers/_tabbroker2.html.erb
<div class="btn-toolbar">
  <div id="nav-broker-cust" class="btn-group nav-tabs" data-toggle="buttons-radio">
		<button class="btn"><i class="icon-search"></i></button>
		<% Time.now.beginning_of_year.strftime("%Y%m").upto(Time.now.end_of_year.strftime("%Y%m")).each do |i| %>
			<%= content_tag "button", :class => "btn", :value => i do %>
				<%= i.at(4..5) %>
			<% end %>
		<% end %>
  </div>
</div>
<div>
	<div class="well">
		<div id="chart_1">
			<%= render 'brokers/brokerchart1' %>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6">
			<div class="well">
				<div id="chart_2">
					<%= render 'brokers/brokerchart2' %>
				</div>
			</div>
		</div>
		<div class="span6">
			<div class="well">
				<div id="chart_3">
					<%= render 'brokers/brokerchart3' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/brokers/_tabbroker3.html.erb
<div class="btn-toolbar">
  <div id="nav-broker-point" class="btn-group nav-tabs" data-toggle="buttons-radio">
		<button class="btn"><i class="icon-search"></i></button>
		<% Time.now.beginning_of_year.strftime("%Y%m").upto(Time.now.end_of_year.strftime("%Y%m")).each do |i| %>
			<%= content_tag "button", :class => "btn", :value => i do %>
				<%= i.at(4..5) %>
			<% end %>
		<% end %>
  </div>
</div>
<div>
	<div class="well">
		<div id="chart_4">
			<%= render 'brokers/brokerchart4' %>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6">
			<div class="well">
				<legend>考核指标</legend>
					<%= render 'brokers/brokertable1' %>
			</div>
		</div>
		<div class="span6">
			<div class="broker-score well">
				<legend>考核结果</legend>
					<%= render 'brokers/brokertable2' %>
			</div>
		</div>
	</div>
</div>

app/views/brokers/_tabbroker4.html.erb
<div class="accordion" id="accordion2">
	<% @salary_months.each do |t| %>
		<div class="accordion-group">
			<div class="accordion-heading">
				<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse<%=t.month_id%>">
					薪酬报告 #<%=t.month_id%>
				</a>
			</div>
			<div id="collapse<%=t.month_id%>" class="collapse in" <% if @salary_months.first.month_id == t.month_id %>style="height: auto;"<% else %>style="height: 0px;"<% end %>>
				<div class="accordion-inner">
					<%= render :partial => 'broker_salary', :locals => { :object => broker_salary(t.month_id) } %>
				</div>
			</div>
		</div>
	<% end %>
</div>​
 

app/views/brokers/_tabbroker5.html.erb
<div id="myCarousel" class="carousel slide">
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item"><%= image_tag("under_construction_1.png") %></div>
    <div class="item"><%= image_tag("under_construction_3.jpg") %></div>
    <div class="item"><%= image_tag("under_construction_2.gif") %></div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

app/views/brokers/index.html.erb
<%= @branch.name %>