config/routes.rb
Cmwp::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :departments, :only => [:index, :show] do
    resources :deptindices do
      get 'dept_index', :on => :member
    end
  end
  resources :branches, :only => [:index, :show] do
    get 'typebrokers', :on => :member
    resources :branchindices do
      get 'branch_index', :on => :member
    end
  end
  resources :brokers, :only => [:index, :show] do
    resources :brokerindices do
      get 'broker_index', :on => :member
    end
    member do
      get :relbrokers
    end
  end
  resources :categories do
    get 'search', :on => :collection
  end
  
  root :to => 'pages#home'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new' 
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'  
  
  match '/todo',    :to => 'pages#todo'  
  
  

end

app/views/layouts/_footer.html.erb
<hr>
<footer>
  <div class="navbar navbar-fixed-bottom">
	 <div class="navbar-inner">
		<div class="container-fluid">
	      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>
		  <!-- Everything you want hidden at 940px or less, place within here -->
	      <div class="nav-collapse">
			<ul class="nav">
				<li><%= link_to "关于", about_path %></li>
				<li><%= link_to "联系我们", contact_path %></li>
				<li><%= link_to "新闻", 'http://www.htsec.com/' %></li>
			</ul>
	        <!-- .nav, .navbar-search, .navbar-form, etc -->
	      </div>
	    </div>
	 </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
 <div class="navbar navbar-fixed-top">
 	<div class="navbar-inner">
		<div class="container-fluid">
	      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>
		  <!-- Everything you want hidden at 940px or less, place within here -->
	      <div class="nav-collapse">
			<ul class="nav pull-right">
				<li><%= link_to "首页", root_path %>
				<% if signed_in? %>
					<li><%= link_to "个人资料", current_user %>
					<li><%= link_to "用户", users_path %>
					<li><%= link_to "设置", edit_user_path(current_user) %>
			 	<% end %>
					<li><%= link_to "帮助", help_path %>
				<% if signed_in? %>
					<li><%= link_to "退出", signout_path %>
				<% else %>
					<li><%= link_to "登录", signin_path %>
				<% end %>
			</ul>
	        <!-- .nav, .navbar-search, .navbar-form, etc -->
	      </div>
	      <!-- Be sure to leave the brand out there if you want it shown -->
		  <a class="brand"><%= logo %></a>
			<% if signed_in? %>
				<%= form_for :categories, :url => search_categories_path,
																	:method => 'get', 
																	:html => { :class => "navbar-search pull-right" } do |f|%>
					<%= f.search_field :category_name,
														 :class => "search-query span2", 
														 :placeholder => "搜索", 
														 :onsearch => true, data: { autocomplete_source: categories_path } %>
					<%= f.submit :type => 'hidden', :name => nil, :value => 'search' %>
				<% end %>
				<!-- <input id="link_broker_id" name="link[broker_id]" type="hidden"/> -->
			<% end %>
	    </div>
	 </div>
 </div>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![end if]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]>
<%= stylesheet_link_tag 'blueprint/ie' %>
<![end if]-->
<%= stylesheet_link_tag 'custom',  :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<!--[if IE]>
		 <script src=
		 "http://html5shiv.googlecode.com/svn/trunk/html5.js">
		 </script>
		<![endif]-->
		<%= include_gon %>
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag	   "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container-fluid">	
			<%= render 'shared/breadcrumb' %>
			<div class="row-fluid">
				<% flash.each do |key, value| %>
				  <div class="alert alert-<%= key %>">
					<a class="close" data-dismiss="alert">×</a>
					<%= value %>
				  </div>	
				<% end %>
				<%= yield %>
			</div>
		</div>
		<%= render 'layouts/footer' %>	
		<!-- <%= debug(params) if Rails.env.development? %> -->
	</body>
<html> 